// Code generated by melt; DO NOT EDIT.

package templates

import (
	"github.com/0-mqix/melt"
	"io"

	"github.com/0-mqix/melt/playground/data"
	"net/http"
)

var (
	TemplatesGlobal *melt.Component
	TemplatesIndex  *melt.Component
)

func Load(furnace *melt.Furnace) {
	TemplatesGlobal = furnace.MustGetComponent("templates/global.html")
	TemplatesIndex = furnace.MustGetComponent("templates/index.html")
}

type TemplatesGlobalData struct {
	Message any
	Name    any
}

// generated write function for component
//
//	path: "templates/global.html"
func WriteTemplatesGlobal(w io.Writer, data TemplatesGlobalData) error {
	return TemplatesGlobal.Write(w, data)
}

type TemplatesIndexData struct {
	Name    data.Data[int]
	Request *http.Request
	Number  int
}

// generated write function for component
//
//	path: "templates/index.html"
func WriteTemplatesIndex(w io.Writer, data TemplatesIndexData) error {
	return TemplatesIndex.Write(w, data)
}
