// Code generated by melt; DO NOT EDIT.

package templates

import (
	"github.com/0-mqix/melt"
	"io"
	"net/http"
)

var (
	Index *melt.Component
)

type GlobalHandlers struct {
}

func Load(furnace *melt.Furnace, handlers GlobalHandlers) {
	Index = furnace.MustGetComponent("templates/index.html")

	globalHandlers := make(map[string]melt.GlobalHandler)

	furnace.SetGlobalHandlers(globalHandlers)
}

type IndexData struct{}

// generated write function for component
//
//	path: "templates/index.html"
func WriteIndex(w io.Writer, r *http.Request, data IndexData, globalOptions ...melt.GlobalOption) error {
	return Index.Write(w, r, data, globalOptions...)
}
